## Import Packages

In [1]:
import xarray as xr
import pandas as pd
import numpy as np
import holoviews as hv
from holoviews import opts
import dask.dataframe as dd
import hvplot.dask  # noqa

import datashader as ds
import numpy as np
import holoviews as hv
import pandas as pd
import numpy as np

from holoviews import opts
from holoviews.operation.datashader import datashade, shade, dynspread, spread
from holoviews.operation.datashader import rasterize, ResamplingOperation
from holoviews.operation import decimate
import polars as pl

hv.extension('bokeh')

ModuleNotFoundError: No module named 'datashader'

# Import Data

In [2]:
# 25 MB chunks 

df15 = dd.read_csv('ssp126_global_daily_2015_2020.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df21 = dd.read_csv('ssp126_global_daily_2021_2030.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df31 = dd.read_csv('ssp126_global_daily_2031_2040.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df41 = dd.read_csv('ssp126_global_daily_2041_2050.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df51 = dd.read_csv('ssp126_global_daily_2051_2060.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df61 = dd.read_csv('ssp126_global_daily_2061_2070.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df71 = dd.read_csv('ssp126_global_daily_2071_2080.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df81 = dd.read_csv('ssp126_global_daily_2081_2090.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df91 = dd.read_csv('ssp126_global_daily_2091_2100.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})

In [3]:
df91

Dask DataFrame Structure:
                 index    time      lat      lon  sfcwind Capacity (MW)    City Local area (taluk, county) Major area (prefecture, district) State/Province  Region Country sfc_wind80m sfc_wind80m_floor
npartitions=261
                 int64  object  float64  float64  float64       float64  string                     string                            string         string  string  string     float64           float64
                   ...     ...      ...      ...      ...           ...     ...                        ...                               ...            ...     ...     ...         ...               ...
...                ...     ...      ...      ...      ...           ...     ...                        ...                               ...            ...     ...     ...         ...               ...
                   ...     ...      ...      ...      ...           ...     ...                        ...                               ...            ...     ...     ...         ...               ...
                   ...     ...      ...      ...      ...           ...     ...                        ...                               ...            ...     ...     ...         ...               ...
Dask Name: read-csv, 1 graph layer

In [4]:
# merge dask dataframe to pandas dataframe
import dask.dataframe as dd
join = dd.concat([df15, df21])
join2 = dd.concat([join, df31])
join3 = dd.concat([join2, df41])
join4 = dd.concat([join3, df51])
join5 = dd.concat([join4, df61])
join6 = dd.concat([join5, df71])
join7 = dd.concat([join6, df81])
SSP126 = dd.concat([join7, df91])

# inspect results
# join.compute()

In [5]:
#display the last 5 rows of SSP126
SSP126.tail()

,index,time,lat,lon,sfcwind,Capacity (MW),City,"Local area (taluk, county)","Major area (prefecture, district)",State/Province,Region,Country,sfc_wind80m,sfc_wind80m_floor
229027,25187,2100-12-27,-34.25,-56.75,3.010519,10.0,Villa Rodriguez,<NA>,<NA>,San José,Americas,Uruguay,4.053062,4.0
229028,25187,2100-12-28,-34.25,-56.75,3.508318,10.0,Villa Rodriguez,<NA>,<NA>,San José,Americas,Uruguay,4.723249,4.5
229029,25187,2100-12-29,-34.25,-56.75,3.665233,10.0,Villa Rodriguez,<NA>,<NA>,San José,Americas,Uruguay,4.934503,4.5
229030,25187,2100-12-30,-34.25,-56.75,3.951515,10.0,Villa Rodriguez,<NA>,<NA>,San José,Americas,Uruguay,5.319926,5.0
229031,25187,2100-12-31,-34.25,-56.75,3.386276,10.0,Villa Rodriguez,<NA>,<NA>,San José,Americas,Uruguay,4.558944,4.5

In [6]:
SSP126['Year'] = SSP126['time'].astype(str).str[:4] # creating year column
SSP126['Year'] = SSP126['Year'].astype(int) 
# add a column that is called 'loc' and it is the combination of lat and lon with a comma in between
SSP126['loc'] = SSP126['lat'].astype(str) + ',' + SSP126['lon'].astype(str)
SSP126.head()

,index,time,lat,lon,sfcwind,Capacity (MW),City,"Local area (taluk, county)","Major area (prefecture, district)",State/Province,Region,Country,sfc_wind80m,sfc_wind80m_floor,Year,loc
0,0,2015-01-01,28.25,-0.25,3.283957,10.0,Kabertene,Tsabit District,<NA>,Adrar,Africa,Algeria,4.421191,4.0,2015,"28.25,-0.25"
1,0,2015-01-02,28.25,-0.25,5.102804,10.0,Kabertene,Tsabit District,<NA>,Adrar,Africa,Algeria,6.869905,6.5,2015,"28.25,-0.25"
2,0,2015-01-03,28.25,-0.25,2.923188,10.0,Kabertene,Tsabit District,<NA>,Adrar,Africa,Algeria,3.935489,3.5,2015,"28.25,-0.25"
3,0,2015-01-04,28.25,-0.25,2.653984,10.0,Kabertene,Tsabit District,<NA>,Adrar,Africa,Algeria,3.573059,3.5,2015,"28.25,-0.25"
4,0,2015-01-05,28.25,-0.25,2.835837,10.0,Kabertene,Tsabit District,<NA>,Adrar,Africa,Algeria,3.817888,3.5,2015,"28.25,-0.25"

In [7]:
# split the 'SSP126' into datasets with the following years: 2015-2039, 2040-2064, 2065-2089, 2090-2100
SSP126_2015_2039 = SSP126[SSP126['Year'].between(2015, 2039, inclusive=True)]
SSP126_2040_2064 = SSP126[SSP126['Year'].between(2040, 2064, inclusive=True)]
SSP126_2065_2089 = SSP126[SSP126['Year'].between(2065, 2089, inclusive=True)]
SSP126_2090_2100 = SSP126[SSP126['Year'].between(2090, 2100, inclusive=True)]

c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)

Apply IEC Class

In [8]:
#group by loc and find the mean sfc_wind80m_floor. Uncomment and run one at a time


#SSP126_2015_2039_iec = SSP126_2015_2039.groupby('loc')['sfc_wind80m_floor'].mean().compute()
#SSP126_2040_2064_iec = SSP126_2040_2064.groupby('loc')['sfc_wind80m_floor'].mean().compute()
#SSP126_2065_2089_iec = SSP126_2065_2089.groupby('loc')['sfc_wind80m_floor'].mean().compute()
SSP126_2090_2100_iec = SSP126_2090_2100.groupby('loc')['sfc_wind80m_floor'].mean().compute()

c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)
c:\Users\Bryn\anaconda3\lib\site-packages\dask\utils.py:1102: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  return getattr(__obj, self.method)(*args, **kwargs)

In [9]:
SSP126_2090_2100_iec

loc
-1.25,36.75      2.832338
-1.75,36.75      3.143266
-2.75,36.75      2.573936
-29.75,22.25     5.600448
-3.75,39.75      5.345158
                   ...
-52.75,-70.75    7.943490
-6.25,-78.75     1.775081
-7.75,-79.25     2.664800
11.75,-71.75     9.237740
12.25,-72.25     8.842918
Name: sfc_wind80m_floor, Length: 3516, dtype: float64

In [10]:
def IEC_Class(s): # s being sfc_wind80m_foor  25-year avg 
    if s < 7.5:
        return 1
    elif  7.5 <= s <= 8.5:
        return 2
    elif s > 8.5:
        return 3

In [11]:
#apply the IEC_Class function to the mean sfc_wind80m_floor in SSP126_2015_2039_iec and name the column 'iec'. Uncomment and run one at a time

#SSP126_2015_2039_iec_n = SSP126_2015_2039_iec.apply(IEC_Class).rename('iec')
#SSP126_2040_2064_iec_n = SSP126_2040_2064_iec.apply(IEC_Class).rename('iec')
#SSP126_2065_2089_iec_n = SSP126_2065_2089_iec.apply(IEC_Class).rename('iec')
SSP126_2090_2100_iec_n = SSP126_2090_2100_iec.apply(IEC_Class).rename('iec')

In [12]:
# merge the two dataframes on loc. Uncomment and run one at a time
 
#SSP126_2015_2039 = dd.merge(SSP126_2015_2039, SSP126_2015_2039_iec_n, on='loc', how='left')
#SSP126_2040_2064 = dd.merge(SSP126_2040_2064, SSP126_2040_2064_iec_n, on='loc', how='left')
#SSP126_2065_2089 = dd.merge(SSP126_2065_2089, SSP126_2065_2089_iec_n, on='loc', how='left')
SSP126_2090_2100 = dd.merge(SSP126_2090_2100, SSP126_2090_2100_iec_n, on='loc', how='left')

In [13]:
#rename 'sfc_wind80m_floor_x' to 'sfc_wind80m_floor'. Uncomment and run one at a time
#SSP126_2015_2039 = SSP126_2015_2039.rename(columns={'sfc_wind80m_floor_x': 'sfc_wind80m_floor'})
#SSP126_2040_2064 = SSP126_2040_2064.rename(columns={'sfc_wind80m_floor_x': 'sfc_wind80m_floor'})
#SSP126_2065_2089 = SSP126_2065_2089.rename(columns={'sfc_wind80m_floor_x': 'sfc_wind80m_floor'})
SSP126_2090_2100 = SSP126_2090_2100.rename(columns={'sfc_wind80m_floor_x': 'sfc_wind80m_floor'})

In [14]:
IEC_Classifications = dd.read_csv('iec_classifications.csv')
# convert IEC_Class to i64
IEC_Classifications.compute()

     iec       CP  sfc_wind80m_floor
0      1  19.3936                3.0
1      1  33.1932                3.5
2      1  37.9232                4.0
3      1  41.4574                4.5
4      1  42.1845                5.0
..   ...      ...                ...
130    3   1.8872               23.0
131    3   1.6623               23.5
132    3   1.4601               24.0
133    3   1.2781               24.5
134    3   1.1140               25.0

[135 rows x 3 columns]

Now we apply the Capacity Factors to each unique IEC Class

In [15]:
# merge the data on 'iec' and 'sfc_wind80m'. Uncomment and run one at a time
#SSP126_2015_2039_n = dd.merge(SSP126_2015_2039, IEC_Classifications, on=['iec', 'sfc_wind80m_floor'], how='left')
#SSP126_2040_2064_n = dd.merge(SSP126_2040_2064, IEC_Classifications, on=['iec', 'sfc_wind80m_floor'], how='left')
#SSP126_2065_2089_n = dd.merge(SSP126_2065_2089, IEC_Classifications, on=['iec', 'sfc_wind80m_floor'], how='left')
SSP126_2090_2100_n = dd.merge(SSP126_2090_2100, IEC_Classifications, on=['iec', 'sfc_wind80m_floor'], how='left')

Organize into the 150 TEM Regions as specified by the ISO-3166-1-2020 Sheet in the DICTIONARY_REGIONS_ISO3166.xlsx

In [16]:
#open 'TEM_Regions.xlsx' in dask
#NOTE: I had to rename some country names [Column G] in this to have them match the countries in the ISIMIP dataset. This included:
# 'Philippines (the)' to 'Philippines'
# 'Korea (the Republic of)' to 'South Korea'
# 'Taiwan (Province of China)' to 'Taiwan'
# 'Viet Nam' to 'Vietnam'
# 'Dominican Republic (the)' to 'Dominican Republic'
# 'Turkey' to 'Türkiye'
# 'Czechia' to 'Czech Republic'
# 'Faroe Islands (the)' to 'Faroe Islands'
# 'Netherlands (the)' to 'Netherlands'
# 'Russian Federation (the)' to 'Russia'
# 'United Kingdom of Great Britain and Northern Ireland (the)' to 'United Kingdom'
# 'Iran (Islamic Republic of)' to 'Iran'
# 'United States of America (the)' to 'United States'
# 'Bolivia (Plurinational State of)' to 'Bolivia'

# Kosovo is not in the TEM Regions Dictionary, so it will not be included in the final dataset

TEM_Regions = dd.read_csv('TEM_Regions.csv', assume_missing=True)
# only keep the 'TEMELE_REGIONS_COPY' and 'Country' columns
TEM_Regions = TEM_Regions[['TEMELE_REGIONS_COPY', 'Country']]
TEM_Regions.compute()

    TEMELE_REGIONS_COPY                                     Country
0                   AFO                                     Burundi
1                   AFO                               Comoros (the)
2                   AFO                                    Djibouti
3               AFE_ERI                                     Eritrea
4               AFE_ETH                                    Ethiopia
..                  ...                                         ...
244                 NaN                              Norfolk Island
245                 NaN                                    Pitcairn
246                 NaN                      Svalbard and Jan Mayen
247                 NaN           French Southern Territories (the)
248                 NaN  United States Minor Outlying Islands (the)

[249 rows x 2 columns]

In [17]:
#combine the TEM_Regions and SSP dataframes on 'Country'. Uncomment and run one at a time
#SSP126_2015_2039_t = dd.merge(SSP126_2015_2039_n, TEM_Regions, on='Country', how='left')
#SSP126_2040_2064_t = dd.merge(SSP126_2040_2064_n, TEM_Regions, on='Country', how='left')
#SSP126_2065_2089_t = dd.merge(SSP126_2065_2089_n, TEM_Regions, on='Country', how='left')
SSP126_2090_2100_t = dd.merge(SSP126_2090_2100_n, TEM_Regions, on='Country', how='left')

In [18]:
#drop any rows where the country is 'Kosovo'. Uncomment and run one at a time
#SSP126_2015_2039_tt = SSP126_2015_2039_t[SSP126_2015_2039_t['Country'] != 'Kosovo']
#SSP126_2040_2064_tt = SSP126_2040_2064_t[SSP126_2040_2064_t['Country'] != 'Kosovo']
#SSP126_2065_2089_tt = SSP126_2065_2089_t[SSP126_2065_2089_t['Country'] != 'Kosovo']
SSP126_2090_2100_tt = SSP126_2090_2100_t[SSP126_2090_2100_t['Country'] != 'Kosovo']

In [19]:
# average the CP by TEMELE_REGIONS_COPY and time. Uncomment and run one at a time
#SSP126_2015_2039_tt = SSP126_2015_2039_tt.groupby(['TEMELE_REGIONS_COPY', 'time'])['CP'].mean().compute()
#SSP126_2040_2064_tt = SSP126_2040_2064_tt.groupby(['TEMELE_REGIONS_COPY', 'time'])['CP'].mean().compute()
#SSP126_2065_2089_tt = SSP126_2065_2089_tt.groupby(['TEMELE_REGIONS_COPY', 'time'])['CP'].mean().compute()
SSP126_2090_2100_tt = SSP126_2090_2100_tt.groupby(['TEMELE_REGIONS_COPY', 'time'])['CP'].mean().compute()

In [20]:
SSP126_2090_2100_tt.head()

TEMELE_REGIONS_COPY  time
AFE_ETH              2090-01-01    33.19320
                     2090-01-02    24.91344
                     2090-01-03    19.39360
                     2090-01-04    19.39360
                     2090-01-05    19.39360
Name: CP, dtype: float64

In [21]:
#save to csv. Uncomment and run one at a time

#SSP126_2015_2039_tt.to_csv('SSP126_2015_2039_test.csv')
#SSP126_2040_2064_tt.to_csv('SSP126_2040_2064_test.csv')
#SSP126_2065_2089_tt.to_csv('SSP126_2065_2089_test.csv')
SSP126_2090_2100_tt.to_csv('SSP126_2090_2100_test.csv')

Organize in the Format that is compliant with TIMES/VEDA 2.0 --> Only Run the Block associated with the proper SSP

In [22]:
# dask open csv
#SSP126_2015_2039_tt = dd.read_csv('SSP126_2015_2039_test.csv', assume_missing=True)
#SSP126_2040_2064_tt = dd.read_csv('SSP126_2040_2064_test.csv', assume_missing=True)
#SSP126_2065_2089_tt = dd.read_csv('SSP126_2065_2089_test.csv', assume_missing=True)
SSP126_2090_2100_tt = dd.read_csv('SSP126_2090_2100_test.csv', assume_missing=True)

# 2015-2039

In [ ]:
#   SSP 126 2015-2039
#create a new column called 'Month' that is the month of the 'time' column
SSP126_2015_2039_tt['Month'] = SSP126_2015_2039_tt['time'].astype(str).str[5:7]
#create a new column called 'Day' that is the day of the 'time' column
SSP126_2015_2039_tt['Day'] = SSP126_2015_2039_tt['time'].astype(str).str[8:10]
#create a new column called 'TimeSlice' that is 'M' + Month + 'D' + Day
SSP126_2015_2039_tt['TimeSlice'] = 'M' + SSP126_2015_2039_tt['Month'] + 'D' + SSP126_2015_2039_tt['Day']
# add a new column called 'Attribute' that is entirely full of 'RNW'
SSP126_2015_2039_tt['Attribute'] = 'RNW'
# add a new column called 'Yr' that is the year of the 'time' column
SSP126_2015_2039_tt['Yr'] = SSP126_2015_2039_tt['time'].astype(str).str[:4]
# add a new column called 'PSET_CI' that is 'ELCWNO' for onshore or 'ELCWNF' for offshore
SSP126_2015_2039_tt['PSET_CI'] = 'ELCWNO'

SSP126_2015_2039_tt= SSP126_2015_2039_tt.groupby(['State/Province', 'time']).first().compute()
#pivot the table so that TEMELE_REGIONS_COPY are the columns, TimeSlice are the rows, and the values are the CP
SSP126_2015_2039_tt = SSP126_2015_2039_tt.pivot_table(index=['TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_PN'], columns='State/Province', values='CP', aggfunc='first')
#replace all NaN values with 0
SSP126_2015_2039_tt = SSP126_2015_2039_tt.fillna(0)
SSP126_2015_2039_tt

In [88]:
#export to csv
SSP126_2015_2039_tt.to_csv('SSP126_2015_2039_TIMES.csv')

# 2040-2064

In [34]:
#   SSP 126 2040-2064
#create a new column called 'Month' that is the month of the 'time' column
SSP126_2040_2064_tt['Month'] = SSP126_2040_2064_tt['time'].astype(str).str[5:7]
#create a new column called 'Day' that is the day of the 'time' column
SSP126_2040_2064_tt['Day'] = SSP126_2040_2064_tt['time'].astype(str).str[8:10]
#create a new column called 'TimeSlice' that is 'M' + Month + 'D' + Day
SSP126_2040_2064_tt['TimeSlice'] = 'M' + SSP126_2040_2064_tt['Month'] + 'D' + SSP126_2040_2064_tt['Day']
# add a new column called 'Attribute' that is entirely full of 'RNW'
SSP126_2040_2064_tt['Attribute'] = 'RNW'
# add a new column called 'Yr' that is the year of the 'time' column
SSP126_2040_2064_tt['Yr'] = SSP126_2040_2064_tt['time'].astype(str).str[:4]
# add a new column called 'PSET_CI' that is 'ELCWNO' for onshore or 'ELCWNF' for offshore
SSP126_2040_2064_tt['PSET_CI'] = 'ELCWNO'

SSP126_2040_2064_tt= SSP126_2040_2064_tt.groupby(['State/Province', 'time']).first().compute()
#pivot the table so that TEMELE_REGIONS_COPY are the columns, TimeSlice are the rows, and the values are the CP
SSP126_2040_2064_tt = SSP126_2040_2064_tt.pivot_table(index=['TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_PN'], columns='State/Province', values='CP', aggfunc='first')
#replace all NaN values with 0
SSP126_2040_2064_tt = SSP126_2040_2064_tt.fillna(0)

#sort by the 'Yr' column
SSP126_2040_2064_tt = SSP126_2040_2064_tt.sort_values(by=['time'])
SSP126_2040_2064_tt

,,,,,,TEMELE_REGIONS_COPY,AFE_ETH,AFE_KEN,AFN_DZA,AFN_EGY,AFN_MAR,AFN_TUN,AFO,AFW_NGA,AFW_SEN,ANZ_AUS,...,SAS_BOL,SAS_CHL,SAS_COL,SAS_ECU,SAS_PER,SAS_URY,SAU_SAU,TUR_TUR,USA_USA,ZAF_ZAF
TimeSlice,Yr,Month,Day,time,Attribute,PSET_PN,,,,,,,,,,,,,,,,,,,,,
M01D01,2040,01,01,2040-01-01,RNW,ELE_WIN,33.19320,0.000000,43.6877,27.947169,43.855500,19.393600,43.8555,37.9232,43.813550,36.875778,...,26.293400,36.273051,44.228033,0.0,37.524260,42.120874,42.1845,36.896100,37.203858,37.131647
M01D02,2040,01,02,2040-01-02,RNW,ELE_WIN,33.19320,33.193200,43.6877,39.949980,39.101267,43.743633,44.8366,41.4574,44.888425,38.270245,...,19.393600,39.337865,37.824000,0.0,40.916660,41.842288,0.0000,35.950510,41.273502,33.532258
M01D03,2040,01,03,2040-01-03,RNW,ELE_WIN,33.19320,29.565360,44.9057,36.976346,35.589667,44.555633,45.5180,41.4574,45.404975,42.482744,...,41.078700,41.991556,46.630000,0.0,37.960520,45.271268,19.3936,39.159403,39.012755,40.331135
M01D04,2040,01,04,2040-01-04,RNW,ELE_WIN,37.92320,23.336343,44.9057,37.426077,43.687700,37.923200,44.4439,41.4574,45.518000,37.021095,...,44.751767,40.878246,46.081433,0.0,39.949980,41.247361,19.3936,35.317943,36.912137,41.958935
M01D05,2040,01,05,2040-01-05,RNW,ELE_WIN,37.92320,23.336343,43.6877,39.881800,39.106917,39.101267,44.4439,37.9232,45.211300,41.100688,...,0.000000,40.557252,44.992900,0.0,34.924120,37.188440,43.8555,40.494011,37.919398,41.940051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
M12D27,2064,12,27,2064-12-27,RNW,ELE_WIN,19.39360,33.193200,41.4574,22.626520,41.640631,41.457400,45.5714,41.4574,44.591325,30.219591,...,0.000000,34.287398,37.824000,0.0,41.639175,26.141508,37.9232,34.638764,42.379089,42.427078
M12D28,2064,12,28,2064-12-28,RNW,ELE_WIN,19.39360,41.457400,44.9057,37.391954,34.706069,45.518000,45.5180,41.4574,44.100775,41.750148,...,0.000000,31.429667,26.658467,0.0,37.626320,38.722138,43.6877,33.438749,42.535510,37.471491
M12D29,2064,12,29,2064-12-29,RNW,ELE_WIN,24.91344,29.250457,44.4439,39.391350,41.908531,45.211300,45.5180,41.4574,44.836600,42.338163,...,23.993467,26.825841,30.203667,0.0,43.130125,43.718482,41.4574,38.695286,41.045730,41.714406
M12D30,2064,12,30,2064-12-30,RNW,ELE_WIN,37.92320,28.067150,43.6877,0.000000,41.151454,19.393600,45.5714,43.6877,43.729650,43.446124,...,26.293400,31.587716,46.459067,0.0,43.255975,43.412006,43.6877,31.782739,43.066885,42.247414
M12D31,2064,12,31,2064-12-31,RNW,ELE_WIN,33.19320,30.511360,37.9232,35.069070,38.988246,44.070667,45.6123,43.6877,44.853875,42.539428,...,41.822133,36.521452,40.187000,0.0,41.189925,35.020841,37.9232,30.670133,42.480200,38.589115

In [35]:
#export to csv
SSP126_2040_2064_tt.to_csv('SSP126_2040_2064_TIMES.csv')

# 2065-2089

In [25]:
#   SSP 126 2065-2089
#create a new column called 'Month' that is the month of the 'time' column
SSP126_2065_2089_tt['Month'] = SSP126_2065_2089_tt['time'].astype(str).str[5:7]
#create a new column called 'Day' that is the day of the 'time' column
SSP126_2065_2089_tt['Day'] = SSP126_2065_2089_tt['time'].astype(str).str[8:10]
#create a new column called 'TimeSlice' that is 'M' + Month + 'D' + Day
SSP126_2065_2089_tt['TimeSlice'] = 'M' + SSP126_2065_2089_tt['Month'] + 'D' + SSP126_2065_2089_tt['Day']
# add a new column called 'Attribute' that is entirely full of 'RNW'
SSP126_2065_2089_tt['Attribute'] = 'RNW'
# add a new column called 'Yr' that is the year of the 'time' column
SSP126_2065_2089_tt['Yr'] = SSP126_2065_2089_tt['time'].astype(str).str[:4]
# add a new column called 'PSET_CI' that is 'ELCWNO' for onshore or 'ELCWNF' for offshore
SSP126_2065_2089_tt['PSET_CI'] = 'ELCWNO'

SSP126_2065_2089_tt= SSP126_2065_2089_tt.groupby(['State/Province', 'time']).first().compute()
#pivot the table so that TEMELE_REGIONS_COPY are the columns, TimeSlice are the rows, and the values are the CP
SSP126_2065_2089_tt = SSP126_2065_2089_tt.pivot_table(index=['TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_PN'], columns='State/Province', values='CP', aggfunc='first')
#replace all NaN values with 0
SSP126_2065_2089_tt = SSP126_2065_2089_tt.fillna(0)

#sort by the 'Yr' column
SSP126_2065_2089_tt = SSP126_2065_2089_tt.sort_values(by=['time'])
SSP126_2065_2089_tt

,,,,,,TEMELE_REGIONS_COPY,AFE_ETH,AFE_KEN,AFN_DZA,AFN_EGY,AFN_MAR,AFN_TUN,AFO,AFW_NGA,AFW_SEN,ANZ_AUS,...,SAS_BOL,SAS_CHL,SAS_COL,SAS_ECU,SAS_PER,SAS_URY,SAU_SAU,TUR_TUR,USA_USA,ZAF_ZAF
TimeSlice,Yr,Month,Day,time,Attribute,PSET_PN,,,,,,,,,,,,,,,,,,,,,
M01D01,2065,01,01,2065-01-01,RNW,ELE_WIN,0.0000,25.601475,45.5714,43.433777,29.748625,44.699700,45.5714,42.1845,44.591325,38.424304,...,40.572500,32.864310,26.658467,0.0,41.064075,32.124963,43.6877,34.751218,41.095946,36.150781
M01D02,2065,01,02,2065-01-02,RNW,ELE_WIN,19.3936,33.193200,43.8555,39.936675,38.695323,43.235100,45.2113,41.4574,44.853875,43.757561,...,35.558200,36.036080,23.475533,0.0,39.391350,30.903109,33.1932,37.612347,40.257654,39.546359
M01D03,2065,01,03,2065-01-03,RNW,ELE_WIN,33.1932,36.441750,43.8555,0.000000,39.710183,41.839833,44.4439,42.1845,45.072125,42.741068,...,43.733233,39.965762,21.538200,0.0,33.290800,37.849619,19.3936,34.683429,40.763433,37.329803
M01D04,2065,01,04,2065-01-04,RNW,ELE_WIN,33.1932,28.067150,45.5180,42.339720,44.080450,39.359067,45.5714,42.1845,43.729650,41.216425,...,34.345167,38.538798,19.057500,0.0,22.843500,39.814918,42.1845,37.267342,38.361334,39.192360
M01D05,2065,01,05,2065-01-05,RNW,ELE_WIN,33.1932,34.275025,45.2113,39.804560,41.153069,45.580867,44.9057,43.6877,43.687700,39.584439,...,45.313900,29.151746,26.658467,0.0,35.370180,44.544203,37.9232,31.400573,40.431244,37.276240
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
M12D27,2089,12,27,2089-12-27,RNW,ELE_WIN,19.3936,41.457400,0.0000,33.828908,44.521008,43.743633,44.8366,42.1845,43.687700,36.493626,...,40.521700,29.872900,34.023033,0.0,43.130125,32.733697,42.1845,39.591933,38.802115,40.733464
M12D28,2089,12,28,2089-12-28,RNW,ELE_WIN,33.1932,41.457400,19.3936,43.318869,44.880900,43.855500,43.6877,41.4574,43.311900,42.395275,...,0.000000,32.829576,43.046533,0.0,41.457400,35.299800,44.8366,37.265629,38.026723,39.706011
M12D29,2089,12,29,2089-12-29,RNW,ELE_WIN,19.3936,28.593333,0.0000,40.573850,36.488042,44.859633,41.4574,37.9232,42.002725,42.094348,...,0.000000,38.251742,22.506867,0.0,43.687700,38.518988,42.1845,38.882399,31.750605,38.678044
M12D30,2089,12,30,2089-12-30,RNW,ELE_WIN,37.9232,36.346533,43.8555,33.290800,22.029400,43.687700,42.1845,33.1932,42.184500,36.137847,...,0.000000,37.485289,16.942900,0.0,43.437750,35.691147,33.1932,35.362007,38.763130,39.498992
M12D31,2089,12,31,2089-12-31,RNW,ELE_WIN,33.1932,41.457400,41.4574,31.813240,38.758477,41.457400,43.8555,33.1932,42.184500,42.392296,...,28.593333,35.794198,18.352633,0.0,43.130125,41.501394,33.1932,33.081008,38.387390,38.612827

In [26]:
#export to csv
SSP126_2065_2089_tt.to_csv('SSP126_2065_2089_TIMES.csv')

# 2090-2100

In [23]:
#   SSP 126 2090-2100
#create a new column called 'Month' that is the month of the 'time' column
SSP126_2090_2100_tt['Month'] = SSP126_2090_2100_tt['time'].astype(str).str[5:7]
#create a new column called 'Day' that is the day of the 'time' column
SSP126_2090_2100_tt['Day'] = SSP126_2090_2100_tt['time'].astype(str).str[8:10]
#create a new column called 'TimeSlice' that is 'M' + Month + 'D' + Day
SSP126_2090_2100_tt['TimeSlice'] = 'M' + SSP126_2090_2100_tt['Month'] + 'D' + SSP126_2090_2100_tt['Day']
# add a new column called 'Attribute' that is entirely full of 'RNW'
SSP126_2090_2100_tt['Attribute'] = 'RNW'
# add a new column called 'Yr' that is the year of the 'time' column
SSP126_2090_2100_tt['Yr'] = SSP126_2090_2100_tt['time'].astype(str).str[:4]
# add a new column called 'PSET_CI' that is 'ELCWNO' for onshore or 'ELCWNF' for offshore
SSP126_2090_2100_tt['PSET_CI'] = 'ELCWNO'

SSP126_2090_2100_tt= SSP126_2090_2100_tt.groupby(['State/Province', 'time']).first().compute()
#pivot the table so that TEMELE_REGIONS_COPY are the columns, TimeSlice are the rows, and the values are the CP
SSP126_2090_2100_tt = SSP126_2090_2100_tt.pivot_table(index=['TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_PN'], columns='State/Province', values='CP', aggfunc='first')
#replace all NaN values with 0
SSP126_2090_2100_tt = SSP126_2090_2100_tt.fillna(0)

#sort by the 'Yr' column
SSP126_2090_2100_tt = SSP126_2090_2100_tt.sort_values(by=['time'])
SSP126_2090_2100_tt

,,,,,,TEMELE_REGIONS_COPY,AFE_ETH,AFE_KEN,AFN_DZA,AFN_EGY,AFN_MAR,AFN_TUN,AFO,AFW_NGA,AFW_SEN,ANZ_AUS,...,SAS_BOL,SAS_CHL,SAS_COL,SAS_ECU,SAS_PER,SAS_URY,SAU_SAU,TUR_TUR,USA_USA,ZAF_ZAF
TimeSlice,Yr,Month,Day,time,Attribute,PSET_PN,,,,,,,,,,,,,,,,,,,,,
M01D01,2090,01,01,2090-01-01,RNW,ELE_WIN,33.19320,34.846112,42.1845,43.409438,35.518055,44.905700,43.8555,37.9232,43.687700,39.125677,...,19.393600,38.819905,23.475533,0.0,42.246575,29.145913,37.9232,36.112639,40.029371,39.571905
M01D02,2090,01,02,2090-01-02,RNW,ELE_WIN,24.91344,26.874862,45.5180,38.522854,44.341131,44.443900,43.6877,41.4574,42.184500,35.300770,...,0.000000,37.092057,23.475533,0.0,41.457400,40.619115,43.8555,39.900015,40.471915,41.604094
M01D03,2090,01,03,2090-01-03,RNW,ELE_WIN,19.39360,27.670767,45.5714,24.029390,29.230975,45.127600,44.9057,42.1845,44.100775,34.034492,...,19.393600,34.707433,22.648633,0.0,41.639175,41.428921,44.8366,32.964645,42.139165,39.732897
M01D04,2090,01,04,2090-01-04,RNW,ELE_WIN,19.39360,26.748200,44.8366,37.588369,37.496877,0.000000,45.5714,42.1845,44.100775,39.096961,...,42.685567,38.628755,26.658467,0.0,38.806750,43.272238,43.6877,37.884529,40.344329,43.140924
M01D05,2090,01,05,2090-01-05,RNW,ELE_WIN,19.39360,40.279333,19.3936,45.178569,43.603100,0.000000,45.6123,42.1845,44.853875,43.221338,...,44.836600,39.195267,37.824000,0.0,35.259250,43.361009,43.8555,38.517414,38.703784,40.333070
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
M12D27,2100,12,27,2100-12-27,RNW,ELE_WIN,33.19320,34.123540,45.5714,44.781769,31.818608,19.393600,45.5714,44.8366,42.602250,42.511704,...,23.993467,38.743907,46.920133,0.0,41.925750,30.111231,41.1422,33.514676,37.861838,40.839870
M12D28,2100,12,28,2100-12-28,RNW,ELE_WIN,19.39360,28.609600,43.8555,28.307408,32.183933,0.000000,44.9057,43.8555,43.974925,43.409800,...,30.170000,37.864583,46.991533,0.0,36.774060,41.197171,33.1932,37.238146,40.871819,40.906617
M12D29,2100,12,29,2100-12-29,RNW,ELE_WIN,33.19320,34.966950,44.8366,41.809662,42.331658,41.699767,43.8555,42.1845,43.729650,43.360359,...,42.685567,40.374981,46.459067,0.0,38.528240,42.186053,0.0000,40.320524,38.228593,41.948359
M12D30,2100,12,30,2100-12-30,RNW,ELE_WIN,33.19320,36.292275,43.8555,38.366623,25.822650,42.944267,43.8555,41.4574,44.591325,41.446617,...,45.553600,34.549459,46.991533,0.0,43.311900,41.942721,19.3936,36.142953,41.001977,39.131241
M12D31,2100,12,31,2100-12-31,RNW,ELE_WIN,19.39360,36.623525,44.8366,40.158140,29.847500,43.855500,44.9057,33.1932,44.836600,31.675514,...,44.859633,37.975700,46.459067,0.0,42.560300,43.101126,0.0000,35.529929,41.212915,32.570068

In [24]:
#export to csv
SSP126_2090_2100_tt.to_csv('SSP126_2090_2100_TIMES.csv')

#

In [ ]:
# open all the *TIMES.csv files in dask and concatenate them
SSP126_TIMES = dd.read_csv('SSP126_2015_2039_TIMES.csv', assume_missing=True)
SSP126_TIMES = dd.concat([SSP126_TIMES, dd.read_csv('SSP126_2040_2064_TIMES.csv', assume_missing=True)])
SSP126_TIMES = dd.concat([SSP126_TIMES, dd.read_csv('SSP126_2065_2089_TIMES.csv', assume_missing=True)])
SSP126_TIMES = dd.concat([SSP126_TIMES, dd.read_csv('SSP126_2090_2100_TIMES.csv', assume_missing=True)])